Repository ARMmbed/mbed-crypto, pull requests merged in 2019-05, with the labels that each got.

#100 Update to latest Mbed TLS development (as of 2019-05-01)
  include/mbedtls/asn1write.h
  include/mbedtls/bignum.h
  include/mbedtls/padlock.h
  library/aes.c
  library/ccm.c
  library/chacha20.c
  library/des.c
  library/ecp.c
  library/ecp_curves.c
  library/havege.c
  library/md4.c
  library/md5.c
  library/oid.c
  library/poly1305.c
  library/ripemd160.c
  library/sha1.c
  library/sha256.c
  library/sha512.c
  programs/test/benchmark.c
  scripts/abi_check.py
  tests/scripts/all.sh
  tests/scripts/list-identifiers.sh
Labels: enhancement

#98 Curve25519 negative tests
  tests/suites/test_suite_ecp.data
  tests/suites/test_suite_ecp.function
Labels: enhancement

#101 Check unused attributes in import and copy
  include/psa/crypto.h
  library/psa_crypto.c
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
Labels: api-spec, enhancement

#105 Add a link to the seedfile for out-of-tree cmake builds
  tests/CMakeLists.txt
Labels: enhancement

#111 Pass handle parameter last on key creation
  include/psa/crypto.h
  library/psa_crypto.c
  programs/psa/key_ladder_demo.c
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_init.function
  tests/suites/test_suite_psa_crypto_persistent_key.function
  tests/suites/test_suite_psa_crypto_slot_management.function
Labels: api-spec, enhancement, needs: ci

#107 PSA: EC curve size macro
  include/psa/crypto_sizes.h
  library/psa_crypto.c
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto_metadata.function
Labels: bug, enhancement, needs: ci

#108 Add policy usage flag to copy a key
  include/psa/crypto.h
  include/psa/crypto_values.h
  library/psa_crypto.c
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto_slot_management.data
Labels: api-spec, enhancement, needs: ci

#102 Multipart AEAD buffer output sizes
  include/psa/crypto.h
  include/psa/crypto_sizes.h
  include/psa/crypto_values.h
  library/psa_crypto.c
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_metadata.data
  tests/suites/test_suite_psa_crypto_metadata.function
Labels: api-spec, bug, enhancement, needs: ci

#104 Make key ids global and define their range
  include/psa/crypto.h
  include/psa/crypto_types.h
  include/psa/crypto_values.h
  library/psa_crypto.c
  library/psa_crypto_slot_management.c
  library/psa_crypto_slot_management.h
  library/psa_crypto_storage.h
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_persistent_key.function
  tests/suites/test_suite_psa_crypto_slot_management.data
  tests/suites/test_suite_psa_crypto_slot_management.function
Labels: api-spec, enhancement, needs: review

#109 Individual setters for persistent key attributes
  include/psa/crypto.h
  include/psa/crypto_struct.h
  include/psa/crypto_values.h
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_persistent_key.function
  tests/suites/test_suite_psa_crypto_slot_management.function
Labels: api-spec, enhancement, needs: ci

#113 Replace "generator" with "key derivation"
  docs/getting_started.md
  include/psa/crypto.h
  include/psa/crypto_extra.h
  include/psa/crypto_struct.h
  include/psa/crypto_values.h
  library/psa_crypto.c
  library/ssl_cli.c
  library/ssl_tls.c
  programs/psa/key_ladder_demo.c
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
Labels: api-spec, enhancement, needs: review

#112 Remove domain parameters from API 1.0
  include/psa/crypto.h
  include/psa/crypto_extra.h
  include/psa/crypto_sizes.h
  include/psa/crypto_struct.h
  include/psa/crypto_types.h
  include/psa/crypto_values.h
  programs/psa/psa_constant_names.c
  scripts/generate_psa_constants.py
  tests/scripts/test_psa_constant_names.py
  tests/suites/test_suite_psa_crypto_metadata.data
  tests/suites/test_suite_psa_crypto_metadata.function
Labels: api-spec, enhancement, needs: ci, needs: review

#114 Rename KEYPAIR to KEY_PAIR and psa_generate_random_key to psa_generate_key
  docs/getting_started.md
  include/psa/crypto.h
  include/psa/crypto_extra.h
  include/psa/crypto_se_driver.h
  include/psa/crypto_sizes.h
  include/psa/crypto_values.h
  library/pk.c
  library/psa_crypto.c
  library/ssl_cli.c
  programs/psa/crypto_examples.c
  programs/psa/key_ladder_demo.c
  tests/suites/test_suite_pk.function
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_metadata.data
  tests/suites/test_suite_psa_crypto_metadata.function
  tests/suites/test_suite_psa_crypto_persistent_key.data
Labels: api-spec, enhancement, needs: preceding PR, needs: review

#119 PSA 1.0 beta3 minor fixes
  include/psa/crypto.h
  include/psa/crypto_sizes.h
  include/psa/crypto_types.h
  include/psa/crypto_values.h
Labels: api-spec, bug

#121 Fix unlinked macros in API spec
  include/psa/crypto.h
  include/psa/crypto_values.h
Labels: api-spec, bug

#118 Update to latest Mbed TLS development (as of 2019-05-21)
  .gitignore
  .globalrc
  CMakeLists.txt
  Makefile
  include/mbedtls/md.h
  include/mbedtls/oid.h
  library/oid.c
  scripts/abi_check.py
  tests/suites/test_suite_oid.data
  tests/suites/test_suite_oid.function
  tests/suites/test_suite_rsa.data
Labels: enhancement

#123 Update link to PSA Crypto API HTML
  README.md
Labels: bug, needs: review

#124 Makefile: Use full paths to refer to parent files
  library/Makefile
Labels: bug

#127 Allow publishing of folders starting with `_`
  docs/.nojekyll
Labels: enhancement

#125 Fix PSA Crypto API links in README
  README.md
Labels: bug

#128 Implementation-specific extension: Keys may allow a second algorithm
  include/psa/crypto_extra.h
  include/psa/crypto_struct.h
  library/psa_crypto.c
  library/psa_crypto_storage.c
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_persistent_key.data
  tests/suites/test_suite_psa_crypto_persistent_key.function
  tests/suites/test_suite_psa_crypto_slot_management.data
  tests/suites/test_suite_psa_crypto_slot_management.function
Labels: api-spec, enhancement, needs: review
