Repository ARMmbed/mbed-crypto, pull requests merged in 2019-10, with the labels that each got.

#278 Fix on target test issues
  tests/suites/target_test.function
  tests/suites/test_suite_pk.function
  tests/suites/test_suite_pkcs1_v15.function
  tests/suites/test_suite_pkcs1_v21.function
  tests/suites/test_suite_rsa.data
  tests/suites/test_suite_rsa.function
Labels: enhancement

#286 Fix defgroup syntax for API version section
  include/psa/crypto.h
Labels: api-spec, bug

#75 ASN.1 tests without x509
  include/mbedtls/asn1.h
  include/mbedtls/asn1write.h
  library/asn1parse.c
  library/asn1write.c
  library/error.c
  tests/CMakeLists.txt
  tests/suites/helpers.function
  tests/suites/host_test.function
  tests/suites/target_test.function
  tests/suites/test_suite_asn1parse.data
  tests/suites/test_suite_asn1parse.function
  tests/suites/test_suite_asn1write.data
  tests/suites/test_suite_asn1write.function
Labels: enhancement, needs: review

#285 SE driver: make persistent data work
  include/psa/crypto_extra.h
  include/psa/crypto_se_driver.h
  library/psa_crypto.c
  library/psa_crypto_se.c
  library/psa_crypto_se.h
  tests/suites/test_suite_psa_crypto_se_driver_hal.data
  tests/suites/test_suite_psa_crypto_se_driver_hal.function
  tests/suites/test_suite_psa_crypto_se_driver_hal_mocks.data
  tests/suites/test_suite_psa_crypto_se_driver_hal_mocks.function
Labels: enhancement

#279 Include IANA reference in the definition of ECC curves and DH groups
  include/psa/crypto_extra.h
  include/psa/crypto_types.h
  include/psa/crypto_values.h
Labels: api-spec, needs: review

#287 DRBG documentation improvements
  include/mbedtls/config.h
  include/mbedtls/ctr_drbg.h
  include/mbedtls/hmac_drbg.h
  library/version_features.c
  programs/test/query_config.c
  scripts/config.pl
Labels: enhancement

#297 Fix int overflow in mbedtls_asn1_get_int
  library/asn1parse.c
  tests/suites/test_suite_asn1parse.data
  tests/suites/test_suite_asn1parse.function
Labels: bug, needs: review

#301 Create PSA landing pages
  docs/Makefile
  docs/psa/accel/index.html
  docs/psa/accel/index.md
  docs/psa/entropy/index.html
  docs/psa/entropy/index.md
  docs/psa/index.html
  docs/psa/index.md
  docs/psa/se/index.html
  docs/psa/se/index.md
Labels: enhancement, web pages

#299 Allow xxx_drbg_set_entropy_len before xxx_drbg_seed
  include/mbedtls/ctr_drbg.h
  include/mbedtls/hmac_drbg.h
  library/ctr_drbg.c
  library/hmac_drbg.c
  tests/suites/test_suite_ctr_drbg.function
Labels: bug, needs: backports

#304 Make sure Asan failures are detected in 'make test'
  tests/scripts/all.sh
  tests/scripts/run-test-suites.pl
  tests/suites/test_suite_psa_crypto_se_driver_hal.function
Labels: bug, needs: review

#259 Check `len` against buffers size upper bound in PSA tests
  tests/suites/test_suite_psa_crypto.function
Labels: enhancement

#288 Add ECDSA tests with hash and key of different lengths
  tests/suites/test_suite_psa_crypto.data
Labels: enhancement
