Repository ARMmbed/mbed-crypto, pull requests merged in 2019-02, with the labels that each got.

#41 Make further adaptations to new EC public key format
  include/mbedtls/psa_util.h
  library/pkwrite.c
  tests/suites/test_suite_pk.function
Labels: bug

#44 Fix double return statement in cipher.c
  library/cipher.c
Labels: bug

#20 New function psa_copy_key
  include/psa/crypto.h
  library/psa_crypto.c
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_slot_management.data
  tests/suites/test_suite_psa_crypto_slot_management.function
Labels: enhancement

#52 all.sh: Enable verbose failure messages for CMake
  tests/scripts/all.sh
Labels: enhancement

#46 psa: Test fresh contexts have default behavior
  tests/suites/test_suite_psa_crypto.function
Labels: bug

#56 psa_constant_names: status is signed
  programs/psa/psa_constant_names.c
  tests/scripts/test_psa_constant_names.py
Labels: bug, needs: review

#55 Modify PSA related error codes and types
  include/psa/crypto.h
  include/psa/crypto_extra.h
  include/psa/crypto_se_driver.h
  include/psa/crypto_types.h
  include/psa/crypto_values.h
  library/psa_crypto.c
  library/psa_crypto_slot_management.c
  library/psa_crypto_storage.h
  library/psa_crypto_storage_backend.h
  library/psa_crypto_storage_file.c
  library/psa_crypto_storage_its.c
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_entropy.function
  tests/suites/test_suite_psa_crypto_persistent_key.function
  tests/suites/test_suite_psa_crypto_slot_management.data
  tests/suites/test_suite_psa_crypto_slot_management.function
  tests/suites/test_suite_psa_crypto_storage_file.data
Labels: compliance, needs: review

#57 psa: Check generator validity before read
  library/psa_crypto.c
  tests/suites/test_suite_psa_crypto.function
Labels: bug, compliance, needs: review

#11 Document that multipart operation setup can return BAD_STATE
  include/psa/crypto.h
Labels: enhancement, needs: review

#61 travis: Use seed 4 when running ssl-opt.sh
  .travis.yml
Labels: bug

#32 Prepare support for 64 bit key ids under SPM
  library/psa_crypto.c
  library/psa_crypto_service_integration.h
  library/psa_crypto_slot_management.c
  library/psa_crypto_storage.c
  library/psa_crypto_storage_its.c
  visualc/VS2010/mbedTLS.vcxproj
Labels: needs: review

#62 Improve multipart cipher tests: 2 blocks, CTR
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
Labels: enhancement

#59 Support key file IDs encoding the key owner
  include/mbedtls/config.h
  include/psa/crypto_platform.h
  include/psa/crypto_types.h
  library/psa_crypto_core.h
  library/psa_crypto_slot_management.c
  library/psa_crypto_storage.c
  library/psa_crypto_storage.h
  library/psa_crypto_storage_backend.h
  library/psa_crypto_storage_file.c
  library/psa_crypto_storage_its.c
  library/version_features.c
  scripts/config.pl
Labels: enhancement, needs: ci

#65 psa: Be compatible with deprecated constants
  library/psa_crypto.c
Labels: enhancement, needs: ci

#64 Update the architecture document regarding key file identifiers
  docs/architecture/mbed-crypto-storage-specification.md
Labels: bug, needs: review

#67 psa: Add backwards compatible error codes
  include/psa/crypto_extra.h
  scripts/generate_psa_constants.py
  tests/scripts/test_psa_constant_names.py
Labels: enhancement

#58 Disallow use of invalid contexts
  library/cipher.c
  library/psa_crypto.c
  library/ssl_tls.c
  library/x509_crt.c
  library/x509write_csr.c
  programs/psa/crypto_examples.c
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
Labels: bug, compliance, needs: review

#70 psa: Explicitly include platform_util.h
  include/psa/crypto_extra.h
Labels: bug

#72 Fix missing cleanup in psa_cipher_setup
  library/psa_crypto.c
  tests/suites/test_suite_psa_crypto.function
Labels: bug, needs: review
