Repository ARMmbed/mbed-crypto, pull requests merged in 2019-06, with the labels that each got.

#133 Allow DHM selftest to run if MBEDTLS_PEM_PARSE_C is unset
  library/dhm.c
Labels: enhancement

#131 Remove old key creation functions and update cipher and pk
  include/mbedtls/cipher_internal.h
  include/mbedtls/pk.h
  include/psa/crypto_extra.h
  library/cipher.c
  library/pk.c
  library/pk_wrap.c
  library/pkwrite.c
  library/psa_crypto.c
  library/psa_crypto_slot_management.c
  library/psa_crypto_slot_management.h
  programs/psa/crypto_examples.c
  programs/psa/key_ladder_demo.c
  tests/suites/test_suite_pk.function
  tests/suites/test_suite_psa_crypto_slot_management.function
Labels: api-spec, enhancement, needs: review

#138 psa: Add NV seed as an entropy source when needed
  library/psa_crypto.c
Labels: bug

#142 psa: Avoid use of relative include paths
  include/psa/crypto_platform.h
  include/psa/crypto_sizes.h
  include/psa/crypto_struct.h
Labels: bug

#143 test: Check empty buffer decryption for chachapoly
  tests/suites/test_suite_cipher.aes.data
  tests/suites/test_suite_cipher.chacha20.data
  tests/suites/test_suite_cipher.chachapoly.data
  tests/suites/test_suite_cipher.function
Labels: bug

#148 Make test suites compatible with #include <assert.h>
  tests/suites/helpers.function
  tests/suites/host_test.function
  tests/suites/target_test.function
Labels: enhancement, needs: review

#153 Remove unused functions from test_suite_psa_crypto
  tests/suites/test_suite_psa_crypto.function
Labels: enhancement

#132 Test that closing a handle reclaims its resources
  include/psa/crypto_extra.h
  library/psa_crypto_slot_management.c
  tests/Makefile
  tests/psa_crypto_helpers.h
  tests/psa_helpers.h
  tests/suites/helpers.function
  tests/suites/test_suite_pk.function
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_entropy.function
  tests/suites/test_suite_psa_crypto_hash.function
  tests/suites/test_suite_psa_crypto_init.function
  tests/suites/test_suite_psa_crypto_persistent_key.function
  tests/suites/test_suite_psa_crypto_slot_management.data
  tests/suites/test_suite_psa_crypto_slot_management.function
  tests/suites/test_suite_psa_its.function
Labels: api-spec, enhancement, needs: review
