Repository ARMmbed/mbed-crypto, pull requests merged in 2019-04, with the labels that each got.

#89 Update with the latest changes from Mbed TLS development
  ChangeLog
  doxygen/input/doc_mainpage.h
  doxygen/mbedtls.doxyfile
  include/mbedtls/bignum.h
  include/mbedtls/check_config.h
  include/mbedtls/config.h
  include/mbedtls/ecdh.h
  include/mbedtls/ecp.h
  include/mbedtls/oid.h
  include/mbedtls/version.h
  library/CMakeLists.txt
  library/bignum.c
  library/ecdh.c
  library/ecp.c
  library/oid.c
  library/version_features.c
  programs/test/query_config.c
  tests/CMakeLists.txt
  tests/scripts/all.sh
  tests/suites/test_suite_ecdh.data
  tests/suites/test_suite_ecdh.function
  tests/suites/test_suite_ecp.data
  tests/suites/test_suite_ecp.function
  tests/suites/test_suite_mpi.data
  tests/suites/test_suite_mpi.function
  tests/suites/test_suite_oid.data
  tests/suites/test_suite_oid.function
  tests/suites/test_suite_version.data
Labels: DO NOT MERGE, enhancement

#90 Use Windows-specific renaming function
  library/psa_its_file.c
Labels: bug

#95 Update Mbed Crypto with the latest changes from Mbed TLS
  .pylint
  .pylintrc
  .travis.yml
  ChangeLog
  circle.yml
  include/mbedtls/cipher.h
  include/mbedtls/config.h
  include/mbedtls/oid.h
  include/mbedtls/ssl.h
  include/mbedtls/x509_crt.h
  library/bignum.c
  library/cipher.c
  library/cipher_wrap.c
  library/oid.c
  library/ssl_srv.c
  library/ssl_tls.c
  library/version_features.c
  library/x509.c
  library/x509_crt.c
  programs/Makefile
  programs/README.md
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_mail_client.c
  programs/ssl/ssl_server2.c
  programs/test/CMakeLists.txt
  programs/test/cpp_dummy_build.cpp
  programs/test/query_config.c
  programs/test/ssl_cert_test.c
  scripts/abi_check.py
  tests/CMakeLists.txt
  tests/data_files/Makefile
  tests/scripts/all.sh
  tests/scripts/check-files.py
  tests/scripts/check-python-files.sh
  tests/scripts/generate_test_code.py
  tests/scripts/mbedtls_test.py
  tests/scripts/test_generate_test_code.py
  tests/suites/test_suite_cipher.function
  tests/suites/test_suite_cipher.nist_kw.data
  tests/suites/test_suite_hkdf.function
  tests/suites/test_suite_mpi.data
  tests/suites/test_suite_mpi.function
  tests/suites/test_suite_oid.data
  tests/suites/test_suite_oid.function
  visualc/VS2010/mbedTLS.sln
  visualc/VS2010/ssl_cert_test.vcxproj
Labels: DO NOT MERGE, enhancement, needs: review

#97 Use generated source files from Mbed TLS
  library/CMakeLists.txt
  library/Makefile
Labels: bug

#99 Makefile: Remove extra debug print
  library/Makefile
Labels: bug
