Repository ARMmbed/mbed-crypto, pull requests merged in 2019-07, with the labels that each got.

#152 Enable use of Mbed TLS and Mbed Crypto as a CMake subproject
  CMakeLists.txt
  library/CMakeLists.txt
  programs/test/cmake_subproject/.gitignore
  programs/test/cmake_subproject/CMakeLists.txt
  programs/test/cmake_subproject/cmake_subproject.c
  tests/CMakeLists.txt
  tests/scripts/all.sh
Labels: enhancement

#155 Secure element driver registration
  include/mbedtls/check_config.h
  include/mbedtls/config.h
  include/psa/crypto_se_driver.h
  library/CMakeLists.txt
  library/Makefile
  library/psa_crypto.c
  library/psa_crypto_se.c
  library/psa_crypto_se.h
  library/version_features.c
  programs/test/query_config.c
  scripts/config.pl
  tests/CMakeLists.txt
  tests/scripts/all.sh
  tests/suites/test_suite_psa_crypto_se_driver_hal.data
  tests/suites/test_suite_psa_crypto_se_driver_hal.function
  visualc/VS2010/mbedTLS.vcxproj
Labels: api-spec, enhancement

#154 Update TLS 1.2 PRF to multipart API
  include/psa/crypto_extra.h
  include/psa/crypto_struct.h
  include/psa/crypto_values.h
  library/psa_crypto.c
  programs/psa/key_ladder_demo.c
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
Labels: api-spec, enhancement

#160 Iotcrypt 790 update tests to multipart key derivation
  programs/psa/key_ladder_demo.c
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
Labels: api-spec, enhancement, needs: ci, needs: review

#149 Fix misuse of signed ints in the HAVEGE module
  include/mbedtls/havege.h
  library/havege.c
Labels: bug, needs: preceding PR

#167 Documented some algorithms
  include/psa/crypto_values.h
  library/psa_crypto.c
  tests/suites/test_suite_psa_crypto_metadata.data
Labels: api-spec, enhancement

#170 Use stdint.h types
  include/psa/crypto.h
  include/psa/crypto_extra.h
  include/psa/crypto_sizes.h
  include/psa/crypto_struct.h
  library/psa_crypto.c
Labels: api-spec, enhancement, needs: review

#180 PSA Storage: Add psa_trusted_storage_linux persistent storage support for v1.0.0 APIs
  library/psa_crypto_its.h
  library/psa_crypto_storage.c
  library/psa_its_file.c
  tests/suites/test_suite_psa_its.function
Labels: compliance, needs: ci, needs: review

#186 Add CMake option for explicitly link library to trusted_storage
  library/CMakeLists.txt
Labels: enhancement

#157 Secure element key creation foundation
  docs/architecture/mbed-crypto-storage-specification.md
  include/mbedtls/config.h
  include/psa/crypto.h
  include/psa/crypto_se_driver.h
  include/psa/crypto_types.h
  library/psa_crypto.c
  library/psa_crypto_core.h
  library/psa_crypto_se.c
  library/psa_crypto_se.h
  library/psa_crypto_slot_management.c
  library/psa_crypto_slot_management.h
  library/psa_crypto_storage.c
  library/psa_crypto_storage.h
  scripts/config.pl
  tests/scripts/all.sh
  tests/scripts/list-identifiers.sh
  tests/suites/test_suite_psa_crypto_persistent_key.data
  tests/suites/test_suite_psa_crypto_persistent_key.function
  tests/suites/test_suite_psa_crypto_se_driver_hal.data
  tests/suites/test_suite_psa_crypto_se_driver_hal.function
Labels: api-spec, enhancement

#165 Correct version number in storage format spec
  docs/architecture/mbed-crypto-storage-specification.md
Labels: bug
