Repository ARMmbed/mbed-crypto, pull requests merged in 2019-09, with the labels that each got.

#166 Add missing dec_empty_buf tests
  tests/suites/test_suite_cipher.aes.data
  tests/suites/test_suite_cipher.arc4.data
  tests/suites/test_suite_cipher.aria.data
  tests/suites/test_suite_cipher.blowfish.data
  tests/suites/test_suite_cipher.camellia.data
  tests/suites/test_suite_cipher.chachapoly.data
  tests/suites/test_suite_cipher.des.data
  tests/suites/test_suite_cipher.function
  tests/suites/test_suite_cipher.gcm.data
  tests/suites/test_suite_cipher.nist_kw.data
Labels: enhancement

#178 New config.h option to make SHA-512 smaller
  include/mbedtls/config.h
  library/sha512.c
  library/version_features.c
  programs/test/query_config.c
Labels: enhancement

#240 Enable 64-bit bignum limbs and add optimized multiplication for Aarch64
  include/mbedtls/bignum.h
  include/mbedtls/bn_mul.h
Labels: enhancement

#139 Make DES self-test faster, and fix a typo
  include/psa/crypto_platform.h
  library/des.c
Labels: bug, enhancement, needs: review

#242 Technical author review of getting_started.md
  docs/getting_started.md
Labels: enhancement, needs: review

#239 Remove a potential call to fwrite with null buffer. Add UBsan testing
  CMakeLists.txt
  library/psa_its_file.c
  tests/scripts/all.sh
Labels: bug, needs: ci

#222 Check for zero length and NULL buffer pointer.
  library/platform_util.c
Labels: bug

#213 Update function return codes
  include/psa/crypto.h
Labels: api-spec, enhancement

#247 Update the behavior of key handles
  include/psa/crypto.h
Labels: api-spec, enhancement

#117 PSA return status coverage script
  include/psa/crypto.h
  include/psa/crypto_values.h
  tests/.gitignore
  tests/Makefile
  tests/psa_crypto_helpers.h
  tests/scripts/all.sh
  tests/scripts/psa_collect_statuses.py
Labels: enhancement

#185 Remove method dispatch from md
  include/mbedtls/md_internal.h
  library/CMakeLists.txt
  library/Makefile
  library/md.c
  library/md_wrap.c
  visualc/VS2010/mbedTLS.vcxproj
Labels: enhancement, needs: review, needs: work

#210 Remove extra mbedtls_ecp_group_free()
  library/ecp_curves.c
Labels: enhancement, needs: review

#248 Fix a buffer overflow in hmac_setup_internal
  library/psa_crypto.c
  tests/suites/test_suite_psa_crypto.data
Labels: bug, needs: review

#227 Move psa_destroy_key and psa_copy_key to Key Management section
  include/psa/crypto.h
Labels: enhancement

#256 Add missing error case to psa_aead_verify
  include/psa/crypto.h
Labels: api-spec

#257 Forbid zero-length keys
  include/psa/crypto.h
  include/psa/crypto_types.h
  library/psa_crypto.c
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto_persistent_key.data
  tests/suites/test_suite_psa_crypto_se_driver_hal_mocks.function
Labels: bug, enhancement

#115 Improve how generate_psa_constants handles compatibility aliases
  include/psa/crypto_extra.h
  scripts/generate_psa_constants.py
  tests/scripts/test_psa_constant_names.py
Labels: enhancement, needs: review

#260 Update multipart operation documentation
  include/psa/crypto.h
Labels: api-spec

#264 Test the library when malloc(0) returns NULL
  programs/test/selftest.c
  tests/configs/config-wrapper-malloc-0-null.h
  tests/scripts/all.sh
Labels: enhancement, needs: review

#276 Relax input restrictions for key derivation
  include/psa/crypto.h
  include/psa/crypto_struct.h
  include/psa/crypto_values.h
  library/psa_crypto.c
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
Labels: bug

#277 Improve speed of PBKDF2 by caching the digest state of the passphrase
  library/pkcs5.c
Labels: needs: review

#269 Add API versioning
  include/psa/crypto.h
Labels: api-spec
