Repository ARMmbed/mbed-crypto, pull requests merged in 2019-01, with the labels that each got.

#2 PSA tests: use a few common test macros
  tests/suites/helpers.function
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_entropy.function
  tests/suites/test_suite_psa_crypto_hash.function
  tests/suites/test_suite_psa_crypto_init.function
  tests/suites/test_suite_psa_crypto_metadata.function
  tests/suites/test_suite_psa_crypto_persistent_key.function
  tests/suites/test_suite_psa_crypto_slot_management.function
  tests/suites/test_suite_psa_crypto_storage_file.function
Labels: enhancement, needs review

#3 Fix maybe-uninitialized warning
  programs/psa/key_ladder_demo.c
Labels: enhancement

#6 Add initializers for crypto structs
  docs/getting_started.md
  include/psa/crypto.h
  include/psa/crypto_struct.h
  library/psa_crypto.c
  programs/psa/crypto_examples.c
  programs/psa/key_ladder_demo.c
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_hash.function
  tests/suites/test_suite_psa_crypto_persistent_key.function
  tests/suites/test_suite_psa_crypto_slot_management.function
Labels: enhancement, needs: ci

#7 [mbedcrypto] all.sh: make it possible to run a subset of the components
  library/CMakeLists.txt
  tests/scripts/all.sh
  tests/scripts/test_zeroize.gdb
  tests/ssl-opt.sh
Labels: enhancement

#19 Don't require a type and size when creating a key slot
  include/psa/crypto.h
  library/psa_crypto_slot_management.c
  programs/psa/crypto_examples.c
  programs/psa/key_ladder_demo.c
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_persistent_key.function
  tests/suites/test_suite_psa_crypto_slot_management.data
  tests/suites/test_suite_psa_crypto_slot_management.function
Labels: enhancement

#18 New function psa_hash_clone
  include/psa/crypto.h
  library/psa_crypto.c
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_hash.function
Labels: enhancement, needs: ci

#22 Adapting to the new PSA key slot allocation mechanism
  include/mbedtls/cipher_internal.h
  include/mbedtls/pk.h
  include/mbedtls/psa_util.h
  include/mbedtls/ssl.h
  include/mbedtls/ssl_internal.h
  library/cipher.c
  library/pk.c
  library/pk_wrap.c
  library/pkwrite.c
  library/ssl_tls.c
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_server2.c
  tests/suites/test_suite_pk.function
  tests/suites/test_suite_x509write.function
Labels: enhancement, needs: ci, needs: review

#13 Simplify RSA and EC public key formats
  include/psa/crypto.h
  include/psa/crypto_sizes.h
  library/psa_crypto.c
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_persistent_key.data
Labels: enhancement, needs: review

#15 Support wildcard hash in signature policies
  include/psa/crypto_values.h
  library/psa_crypto.c
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_metadata.data
  tests/suites/test_suite_psa_crypto_metadata.function
Labels: enhancement
