Repository ARMmbed/mbed-crypto, pull requests merged in 2019-08, with the labels that each got.

#199 Return right error code.
  library/psa_crypto.c
Labels: bug, needs: ci

#191 Secure element keys: save the key size
  include/psa/crypto_se_driver.h
  library/psa_crypto.c
  library/psa_crypto_core.h
  library/psa_crypto_slot_management.c
  tests/suites/test_suite_psa_crypto_se_driver_hal.function
Labels: api-spec, enhancement

#204 Bring in changes from Mbed TLS as of 2019-08-06
  scripts/abi_check.py
  tests/data_files/Makefile
  tests/data_files/rsa_pkcs1_1024_clear.pem
  tests/suites/helpers.function
  tests/suites/host_test.function
  tests/suites/main_test.function
Labels: bug, enhancement, needs: review

#182 Replace some macros by functions in ecp
  library/ecp.c
Labels: enhancement

#201 Add slot number attribute
  include/psa/crypto_extra.h
  include/psa/crypto_se_driver.h
  include/psa/crypto_struct.h
  include/psa/crypto_types.h
  library/psa_crypto.c
  library/psa_crypto_core.h
  library/psa_crypto_slot_management.c
  library/psa_crypto_slot_management.h
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_se_driver_hal.function
Labels: api-spec, enhancement

#192 Add some negative tests for policy checks
  tests/suites/test_suite_psa_crypto.data
Labels: api-spec, enhancement, needs: review

#183 Secure element key registration
  include/psa/crypto_extra.h
  include/psa/crypto_se_driver.h
  library/psa_crypto.c
  library/psa_crypto_se.c
  library/psa_crypto_se.h
  tests/suites/test_suite_psa_crypto_se_driver_hal.data
  tests/suites/test_suite_psa_crypto_se_driver_hal.function
Labels: api-spec, enhancement

#211 Add hooks for generate and sign in a secure element
  include/psa/crypto_se_driver.h
  library/psa_crypto.c
  tests/suites/test_suite_psa_crypto_se_driver_hal.data
  tests/suites/test_suite_psa_crypto_se_driver_hal.function
Labels: api-spec, enhancement

#221 SE keys: fix psa_destroy_key; add Github issue numbers for missing code
  include/psa/crypto_struct.h
  library/psa_crypto.c
  tests/suites/test_suite_psa_crypto_se_driver_hal.function
Labels: api-spec, bug, enhancement

#144 Fix full build including non-boolean with Asan: crypto part
  tests/suites/test_suite_cipher.function
  tests/suites/test_suite_entropy.function
  tests/suites/test_suite_nist_kw.function
  tests/suites/test_suite_pk.function
Labels: bug

#184 Fix fragile method for passing from ECDSA to ECP restart contexts
  library/ecdsa.c
Labels: bug

#196 Fix the license header of hkdf
  include/mbedtls/hkdf.h
Labels: bug

#230 Remove double underscores from macro and add a check for it
  include/psa/crypto_values.h
  tests/scripts/check-names.sh
  tests/scripts/test_psa_constant_names.py
Labels: bug

#174 Add mock tests for hooks for secure element drivers
  library/psa_crypto.c
  tests/CMakeLists.txt
  tests/suites/test_suite_psa_crypto_se_driver_hal_mocks.data
  tests/suites/test_suite_psa_crypto_se_driver_hal_mocks.function
Labels: api-spec, enhancement

#225 Remove a redundant function call
  library/bignum.c
Labels: bug, needs: review

#224 Remove unused TG variable in mbedtls_mpi_gcd()
  library/bignum.c
Labels: bug

#229 Remove legacy psa key derivation
  include/psa/crypto.h
  include/psa/crypto_extra.h
  include/psa/crypto_struct.h
  library/psa_crypto.c
  programs/psa/key_ladder_demo.c
  tests/suites/test_suite_psa_crypto.data
Labels: needs: preceding PR

#232 Make fixes related to using Mbed Crypto as a service
  docs/getting_started.md
  include/psa/crypto_extra.h
  include/psa/crypto_platform.h
  include/psa/crypto_struct.h
  include/psa/crypto_types.h
  include/psa/crypto_values.h
  library/psa_crypto_slot_management.c
Labels: bug

#238 HMAC DRBG: Split entropy-gathering requests to reduce request sizes
  library/hmac_drbg.c
Labels: bug, needs: backports, needs: review
