Repository ARMmbed/mbed-crypto, pull requests merged in 2019-03, with the labels that each got.

#47 Minor API specification fixes after 1.0beta1
  include/psa/crypto.h
  include/psa/crypto_sizes.h
  include/psa/crypto_values.h
Labels: bug, writing

#80 Remove Diffie-Hellman examples
  programs/.gitignore
  programs/Makefile
  programs/README.md
  programs/pkey/CMakeLists.txt
  programs/pkey/dh_client.c
  programs/pkey/dh_server.c
  visualc/VS2010/dh_client.vcxproj
  visualc/VS2010/dh_server.vcxproj
  visualc/VS2010/mbedTLS.sln
Labels: needs: review

#81 PSA Crypto API 1.0 beta2 docs
  README.md
  docs/PSA_Cryptography_API_Reference.pdf
  docs/PSA_Cryptography_API_Specification.pdf
  docs/html/annotated.html
  docs/html/classes.html
  docs/html/crypto_8h.html
  docs/html/crypto_8h_source.html
  docs/html/crypto__sizes_8h.html
  docs/html/crypto__sizes_8h_source.html
  docs/html/crypto__types_8h.html
  docs/html/crypto__types_8h_source.html
  docs/html/crypto__values_8h.html
  docs/html/crypto__values_8h_source.html
  docs/html/dir_7dae9cfde651cd3cb034485ce5e391b9.html
  docs/html/files.html
  docs/html/functions.html
  docs/html/functions_vars.html
  docs/html/globals.html
  docs/html/globals_defs.html
  docs/html/globals_func.html
  docs/html/globals_type.html
  docs/html/graph_legend.html
  docs/html/group__MAC.html
  docs/html/group__aead.html
  docs/html/group__asymmetric.html
  docs/html/group__cipher.html
  docs/html/group__crypto__types.html
  docs/html/group__derivation.html
  docs/html/group__error.html
  docs/html/group__generators.html
  docs/html/group__hash.html
  docs/html/group__import__export.html
  docs/html/group__initialization.html
  docs/html/group__key__lifetimes.html
  docs/html/group__key__management.html
  docs/html/group__platform.html
  docs/html/group__policy.html
  docs/html/group__random.html
  docs/html/index.html
  docs/html/modules.html
  docs/html/search/all_8.js
  docs/html/search/defines_0.js
  docs/html/structpsa__generate__key__extra__rsa-members.html
  docs/html/structpsa__generate__key__extra__rsa.html
  include/psa/crypto.h
  include/psa/crypto_sizes.h
  include/psa/crypto_values.h
Labels: api-spec, enhancement, needs: review

#82 The specification document is now a single PDF
  README.md
Labels: bug, needs: preceding PR, needs: review

#83 API: minor corrections after beta 2
  include/psa/crypto.h
  include/psa/crypto_extra.h
  include/psa/crypto_values.h
Labels: api-spec, writing

#74 Break non-crypto dependencies
  .travis.yml
  CMakeLists.txt
  Makefile
  configs/config-mini-tls1_1.h
  configs/config-psa-crypto.h
  configs/config-thread.h
  include/CMakeLists.txt
  include/mbedtls/asn1.h
  include/mbedtls/config.h
  include/mbedtls/dhm.h
  include/mbedtls/ecp.h
  library/ecp.c
  library/md.c
  programs/Makefile
  programs/pkey/key_app.c
  programs/pkey/rsa_genkey.c
  programs/pkey/rsa_sign_pss.c
  programs/pkey/rsa_verify_pss.c
  programs/psa/crypto_examples.c
  programs/psa/key_ladder_demo.c
  programs/ssl/CMakeLists.txt
  programs/test/CMakeLists.txt
  programs/test/cpp_dummy_build.cpp
  programs/test/query_config.c
  programs/test/selftest.c
  scripts/bump_version.sh
  scripts/generate_query_config.pl
  scripts/generate_visualc_files.pl
  scripts/output_env.sh
  tests/CMakeLists.txt
  tests/Descriptions.txt
  tests/Makefile
  tests/compat.sh
  tests/scripts/all.sh
  tests/scripts/basic-build-test.sh
  tests/scripts/check-generated-files.sh
  tests/scripts/key-exchanges.pl
  tests/scripts/recursion.pl
  tests/scripts/tcp_client.pl
  tests/scripts/test-ref-configs.pl
  tests/scripts/travis-log-failure.sh
  tests/ssl-opt.sh
  tests/suites/test_suite_debug.data
  tests/suites/test_suite_debug.function
  tests/suites/test_suite_ssl.data
  tests/suites/test_suite_ssl.function
  tests/suites/test_suite_x509parse.data
  tests/suites/test_suite_x509parse.function
  tests/suites/test_suite_x509write.data
  tests/suites/test_suite_x509write.function
  visualc/VS2010/query_compile_time_config.vcxproj
  visualc/VS2010/ssl_client2.vcxproj
  visualc/VS2010/ssl_server2.vcxproj
Labels: enhancement

#69 PSA ITS over file
  configs/config-psa-crypto.h
  include/mbedtls/check_config.h
  include/mbedtls/config.h
  include/psa/crypto_extra.h
  library/CMakeLists.txt
  library/Makefile
  library/psa_crypto.c
  library/psa_crypto_its.h
  library/psa_crypto_storage.c
  library/psa_crypto_storage.h
  library/psa_crypto_storage_backend.h
  library/psa_crypto_storage_file.c
  library/psa_crypto_storage_its.c
  library/psa_its_file.c
  library/version_features.c
  programs/test/query_config.c
  scripts/config.pl
  tests/CMakeLists.txt
  tests/scripts/all.sh
  tests/suites/test_suite_psa_crypto_entropy.function
  tests/suites/test_suite_psa_crypto_persistent_key.data
  tests/suites/test_suite_psa_crypto_persistent_key.function
  tests/suites/test_suite_psa_crypto_storage_file.data
  tests/suites/test_suite_psa_crypto_storage_file.function
  tests/suites/test_suite_psa_its.data
  tests/suites/test_suite_psa_its.function
  visualc/VS2010/mbedTLS.vcxproj
Labels: enhancement, needs: review

#87 tests: Add library to include path when used as submodule
  tests/CMakeLists.txt
Labels: bug
