Repository ARMmbed/mbed-crypto, pull requests merged in 2019-11, with the labels that each got.

#305 CTR_DRBG: grab a nonce from the entropy source if needed
  include/mbedtls/ctr_drbg.h
  include/mbedtls/hmac_drbg.h
  library/ctr_drbg.c
  programs/test/benchmark.c
  tests/suites/test_suite_ctr_drbg.data
  tests/suites/test_suite_ctr_drbg.function
  tests/suites/test_suite_hmac_drbg.function
  tests/suites/test_suite_psa_crypto_init.data
  tests/suites/test_suite_psa_crypto_init.function
Labels: bug

#316 Stop transactions from being reentrant
  library/psa_crypto_storage.c
Labels: bug

#317 getting_started: Make it clear that keys are passed in
  docs/getting_started.md
Labels: enhancement

#314 Fix pk_write with EC key to use a constant size for the private value
  library/pkwrite.c
  tests/data_files/ec_256_long_prv.pem
  tests/data_files/ec_521_short_prv.pem
  tests/suites/test_suite_pkwrite.data
Labels: bug

#284 Fix some possibly-undefined variable warnings
  library/entropy.c
  library/hmac_drbg.c
Labels: bug, needs: ci

#315 Define MBEDTLS_PK_SIGNATURE_MAX_SIZE
  include/mbedtls/pk.h
  include/psa/crypto_sizes.h
  library/pk_wrap.c
  programs/pkey/pk_sign.c
  programs/pkey/pk_verify.c
  tests/suites/test_suite_pk.data
  tests/suites/test_suite_pk.function
Labels: bug

#318 Finish side-porting commits from mbedtls-restricted that missed the split
  include/mbedtls/check_config.h
  include/mbedtls/rsa.h
Labels: bug

#308 Small performance improvement of mbedtls_mpi_div_mpi()
  library/bignum.c
Labels: enhancement

#324 test_psa_constant_names: support key agreement, better code structure
  tests/scripts/test_psa_constant_names.py
  tests/suites/test_suite_psa_crypto_metadata.data
  tests/suites/test_suite_psa_crypto_metadata.function
Labels: enhancement

#293 Always gather MBEDTLS_ENTROPY_BLOCK_SIZE bytes of entropy
  library/entropy.c
  tests/suites/test_suite_entropy.data
  tests/suites/test_suite_entropy.function
Labels: bug

#310 Clarify test descriptions in test_suite_memory_buffer_alloc
  tests/suites/test_suite_memory_buffer_alloc.data
  tests/suites/test_suite_memory_buffer_alloc.function
Labels: enhancement, needs: backports

#307 Add ASN.1 ENUMERATED tag support
  include/mbedtls/asn1.h
  include/mbedtls/asn1write.h
  library/asn1parse.c
  library/asn1write.c
  tests/suites/test_suite_asn1parse.data
  tests/suites/test_suite_asn1parse.function
  tests/suites/test_suite_asn1write.data
  tests/suites/test_suite_asn1write.function
Labels: enhancement, needs: review

#328 Remove dependency of crypto_values.h on crypto_extra.h
  include/psa/crypto_extra.h
  include/psa/crypto_values.h
Labels: api-spec, bug
