Repository ARMmbed/mbed-crypto, pull requests merged in 2020-02, with the labels that each got.

#263 Introduce ASN.1 SEQUENCE traversal API
  include/mbedtls/asn1.h
  library/asn1parse.c
  tests/suites/test_suite_asn1parse.data
  tests/suites/test_suite_asn1parse.function
Labels: enhancement, ready for merge

#345 Fix possible error code mangling in psa_mac_verify_finish
  library/psa_crypto.c
Labels: bug, ready for merge

#357 Update Mbed Crypto with latest Mbed TLS changes as of 2020-02-03
  include/mbedtls/error.h
  library/error.c
  programs/aes/aescrypt2.c
  scripts/config.pl
  scripts/data_files/error.fmt
  tests/suites/helpers.function
  tests/suites/host_test.function
Labels: ready for merge

#350 test_suite_asn1parse: improve testing of trailing garbage in parse_prefixes
  tests/suites/test_suite_asn1parse.data
  tests/suites/test_suite_asn1parse.function
Labels: enhancement

#346 Improve robustness and testing of mbedtls_mpi_copy
  library/bignum.c
  tests/suites/test_suite_mpi.data
  tests/suites/test_suite_mpi.function
Labels: enhancement, ready for merge

#365 Change the compatibility API to inline functions
  include/psa/crypto_compat.h
Labels: enhancement

#367 Fix pk_parse_key()'s use of rsa_complete()
  library/pkparse.c
  tests/suites/test_suite_pkparse.data
  tests/suites/test_suite_pkparse.function
Labels: bug, ready for merge

#370 Bump version to Mbed TLS 2.21.0
  doxygen/mbedtls.doxyfile
  include/mbedtls/version.h
  library/CMakeLists.txt
  tests/suites/test_suite_version.data
Labels: ready for merge
