Repository ARMmbed/mbed-crypto, pull requests merged in 2020-03, with the labels that each got.

#369 Drop requirement for a CLA
  CONTRIBUTING.md
  LICENSE
  README.md
  apache-2.0.txt
  dco.txt
Labels: enhancement, ready for merge

#376 Modify path handling in some build scripts to be closer to mbedtls
  programs/Makefile
  scripts/data_files/vs2010-app-template.vcxproj
  scripts/data_files/vs2010-main-template.vcxproj
  scripts/generate_visualc_files.pl
  tests/scripts/all.sh
  tests/scripts/check-names.sh
  visualc/VS2010/aescrypt2.vcxproj
  visualc/VS2010/benchmark.vcxproj
  visualc/VS2010/crypt_and_hash.vcxproj
  visualc/VS2010/crypto_examples.vcxproj
  visualc/VS2010/dh_genprime.vcxproj
  visualc/VS2010/ecdh_curve25519.vcxproj
  visualc/VS2010/ecdsa.vcxproj
  visualc/VS2010/gen_entropy.vcxproj
  visualc/VS2010/gen_key.vcxproj
  visualc/VS2010/gen_random_ctr_drbg.vcxproj
  visualc/VS2010/gen_random_havege.vcxproj
  visualc/VS2010/generic_sum.vcxproj
  visualc/VS2010/hello.vcxproj
  visualc/VS2010/key_app.vcxproj
  visualc/VS2010/key_app_writer.vcxproj
  visualc/VS2010/key_ladder_demo.vcxproj
  visualc/VS2010/mbedTLS.vcxproj
  visualc/VS2010/mpi_demo.vcxproj
  visualc/VS2010/pem2der.vcxproj
  visualc/VS2010/pk_decrypt.vcxproj
  visualc/VS2010/pk_encrypt.vcxproj
  visualc/VS2010/pk_sign.vcxproj
  visualc/VS2010/pk_verify.vcxproj
  visualc/VS2010/psa_constant_names.vcxproj
  visualc/VS2010/query_compile_time_config.vcxproj
  visualc/VS2010/rsa_decrypt.vcxproj
  visualc/VS2010/rsa_encrypt.vcxproj
  visualc/VS2010/rsa_genkey.vcxproj
  visualc/VS2010/rsa_sign.vcxproj
  visualc/VS2010/rsa_sign_pss.vcxproj
  visualc/VS2010/rsa_verify.vcxproj
  visualc/VS2010/rsa_verify_pss.vcxproj
  visualc/VS2010/selftest.vcxproj
  visualc/VS2010/strerror.vcxproj
  visualc/VS2010/zeroize.vcxproj
Labels: enhancement, ready for merge

#377 Fix warning with gcc7 - maximum allocation exceeded
  tests/suites/test_suite_psa_crypto.function
Labels: bug, ready for merge

#392 Have issue and PR templates redirect to Mbed TLS
  .github/issue_template.md
  .github/pull_request_template.md
Labels: ready for merge

#373 Remove temporary allocation in mbedtls_mpi_sub_abs - single subtract implementation
  library/bignum.c
  tests/suites/test_suite_mpi.function
Labels: enhancement, ready for merge

#378 Fix useless calls in PSA crypto metadata tests
  tests/suites/test_suite_psa_crypto_metadata.function
Labels: bug, ready for merge

#375 Build: Updated CMAKE_C_FLAGS for IAR
  CMakeLists.txt
Labels: ready for merge
