Repository ARMmbed/mbed-crypto, pull requests merged in 2020-01, with the labels that each got.

#342 ctr_drbg: Clarify reseed_counter values before seeding
  include/mbedtls/ctr_drbg.h
Labels: enhancement

#348 Bump version to Mbed TLS 2.20.0
  doxygen/mbedtls.doxyfile
  include/mbedtls/version.h
  library/CMakeLists.txt
  library/Makefile
  tests/suites/test_suite_version.data
Labels: needs: review

#354 Fix incrementing pointer instead of value
  library/ecdsa.c
Labels: bug, ready for merge, security

#349 Fix minor defects found by Coverity
  library/cipher.c
  tests/suites/helpers.function
  tests/suites/test_suite_asn1parse.function
  tests/suites/test_suite_ecdsa.function
  tests/suites/test_suite_mpi.function
  tests/suites/test_suite_pk.function
Labels: bug, ready for merge

#179 Add option to build SHA-512 without SHA-384
  include/mbedtls/check_config.h
  include/mbedtls/config.h
  include/mbedtls/md_internal.h
  include/mbedtls/sha512.h
  library/md.c
  library/psa_crypto.c
  library/sha512.c
  library/version_features.c
  programs/test/query_config.c
  scripts/config.py
  tests/scripts/depends-hashes.pl
  tests/suites/test_suite_ecdsa.data
  tests/suites/test_suite_hmac_drbg.misc.data
  tests/suites/test_suite_hmac_drbg.no_reseed.data
  tests/suites/test_suite_hmac_drbg.nopr.data
  tests/suites/test_suite_hmac_drbg.pr.data
  tests/suites/test_suite_md.data
  tests/suites/test_suite_pkcs5.data
  tests/suites/test_suite_pkparse.data
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto_hash.data
  tests/suites/test_suite_rsa.data
  tests/suites/test_suite_shax.data
Labels: enhancement, ready for merge

#327 Implement psa_hash_compute and psa_hash_compare
  include/psa/crypto.h
  library/psa_crypto.c
  tests/scripts/check-test-cases.py
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
Labels: ready for merge

#330 Streamline PSA key type and curve encodings
  docs/getting_started.md
  include/mbedtls/psa_util.h
  include/psa/crypto.h
  include/psa/crypto_compat.h
  include/psa/crypto_extra.h
  include/psa/crypto_sizes.h
  include/psa/crypto_struct.h
  include/psa/crypto_types.h
  include/psa/crypto_values.h
  library/pk.c
  library/pk_wrap.c
  library/pkwrite.c
  library/psa_crypto.c
  library/psa_crypto_storage.c
  programs/psa/psa_constant_names.c
  scripts/generate_psa_constants.py
  tests/scripts/test_psa_constant_names.py
  tests/suites/test_suite_pk.data
  tests/suites/test_suite_pk.function
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_metadata.data
  tests/suites/test_suite_psa_crypto_metadata.function
  tests/suites/test_suite_psa_crypto_persistent_key.data
  tests/suites/test_suite_psa_crypto_persistent_key.function
  tests/suites/test_suite_psa_crypto_se_driver_hal.data
  tests/suites/test_suite_psa_crypto_se_driver_hal.function
  tests/suites/test_suite_psa_crypto_slot_management.data
Labels: needs: preceding PR, ready for merge

#352 Parse RSA parameters DP, DQ and QP from PKCS1 private keys
  library/pkparse.c
  library/rsa.c
Labels: bug, ready for merge
